name: Release Drafter


on:
  workflow_call:
    inputs:
      config-name:
        required: false
        type: string
        default: release-drafter.yaml

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  draft-release:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write
      pull-requests: read

    steps:
      - uses: release-drafter/release-drafter@v5.22.0
        with:
          config-name: ${{ inputs.config-name }}